IOP_BIN = httpclient.irx
IOP_OBJS = exports.o main.o httpclient.o imports.o

IOP_INCS += -I../common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
