name: Build PS2 Launcher

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    defaults:
      run:
        shell: sh
    steps:
    - name: Install dependencies
      run: apk add --no-cache git zip bash make python3

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: git config --global --add safe.directory '*'

    - name: Build
      run: |
        make languages
        make NOT_PACKED=1

    - name: Upload compiled ELF
      uses: actions/upload-artifact@v4
      with:
        name: PS2-Launcher-Compiled
        path: |
          *.ELF
          *.elf
